szkielety_tworzenia_aplikacji/urls.py
from django.contrib import admin
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('wynajem_limuzyn.urls')),
    path('admin/', admin.site.urls)
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wynajem_limuzyn/urls.py
from django.urls import path
from . import views


app_name = 'wynajem_limuzyn'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('search_miasto/', views.search_miasto, name='search_miasto'),
    path('<int:garaz_id>/search_samochod/', views.search_samochod, name='search_samochod'),
    path('<int:samochod_id>/wypozycz/', views.rent_samochod, name='wypozycz'),
    path('<int:samochod_id>/oddaj/', views.give_back_car, name='oddaj')
]

wynajem_limuzyn/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.utils.timezone import now
class Garaz(models.Model):
    miasto = models.CharField(max_length=200)
    kod_pocztowy = models.CharField(max_length=6)
    ulica = models.CharField(max_length=200)
    numer = models.CharField(max_length=10)
    ilosc_samochodow = models.IntegerField(default=0)
    ilosc_dostepnych_samochodow = models.IntegerField(default=0)
    def __str__(self):
        return self.miasto + ", ul. " + self.ulica + " " + self.numer

    class Meta:
        verbose_name = "garaz"
        verbose_name_plural = "garaze"

class Samochod(models.Model):
    garaz = models.ForeignKey(Garaz, on_delete=models.CASCADE)
    marka = models.CharField(max_length=200)
    model = models.CharField(max_length=200)
    liczba_miejsc = models.IntegerField(default=5)
    data_produkcji = models.DateField(default=timezone.now())
    cena = models.DecimalField(max_digits=6, decimal_places=2)
    zdjecie = models.ImageField(upload_to = 'samochody')
    wypozyczony = models.BooleanField(default=False)
    def is_eco(self):
        return self.data_produkcji > datetime.date(2006, 1, 1)
    is_eco.boolean = True
    is_eco.short_description = 'Euro 4'
    def __str__(self):
        return self.marka + " " + self.model

    class Meta:
        verbose_name = "samochod"
        verbose_name_plural = "samochody"

class Wypozyczalnia(models.Model):
    samochod = models.ForeignKey(Samochod, on_delete=models.CASCADE)
    imie = models.CharField(max_length=200)
    nazwisko = models.CharField(max_length=200)
    czas_wypozyczenia_w_h = models.IntegerField(default=1)
    data_wypozyczenia = models.DateTimeField(default=now)
    data_oddania = models.DateTimeField(default=None, blank=True, null=True)
    def __str__(self):
        return self.imie + " " + self.nazwisko
    class Meta:
        verbose_name = "wypozyczalnia"
        verbose_name_plural = "wypozyczalnie"

wynajem_limuzyn/forms.py
from django import forms

from .models import Wypozyczalnia

class RentForm(forms.ModelForm):

    class Meta:
        model = Wypozyczalnia
        fields = ('imie','nazwisko','czas_wypozyczenia_w_h')
        widgets = {
            'imie': forms.TextInput(attrs={'class': 'form-control'}),
            'nazwisko': forms.TextInput(attrs={'class': 'form-control'}),
            'czas_wypozyczenia_w_h': forms.TextInput(attrs={'class': 'form-control'}),
        }

wynajem_limuzyn/views.py
from django.shortcuts import render, redirect
from django.views import generic
from .models import Garaz, Samochod, Wypozyczalnia
from django.shortcuts import render, get_object_or_404
from .forms import RentForm
from django.utils.timezone import now

class IndexView(generic.ListView):
    template_name = 'wynajem_limuzyn/index.html'
    context_object_name = 'garaze'

    def get_queryset(self):
        """
        Zwraca liste dostepnych garazy z limuzynami
        """
        return Garaz.objects.all()

class DetailView(generic.DetailView):
    model = Garaz
    template_name = 'wynajem_limuzyn/detail.html'

def search_miasto(request):
    try:
        if request.GET['miasto'] and request.GET['kod_pocztowy']:
            searched_miasto = Garaz.objects.filter(
                miasto=request.GET['miasto'],
                kod_pocztowy=request.GET['kod_pocztowy']
            )
        elif request.GET['miasto']:
            searched_miasto = Garaz.objects.filter(
                miasto=request.GET['miasto'],
            )
        elif request.GET['kod_pocztowy']:
            searched_miasto = Garaz.objects.filter(
                kod_pocztowy=request.GET['kod_pocztowy'],
            )
        else:
            searched_miasto = Garaz.objects.all
    except (KeyError, Garaz.DoesNotExist):
        return render(request, 'wynajem_limuzyn/index.html', {
            'garaze': None,
            'error_message': "Nie znaleziono garaży w wyszukiwanym mieście.",
        })
    else:
        return render(request, 'wynajem_limuzyn/index.html', {'garaze': searched_miasto})

def search_samochod(request, garaz_id):
    garaz = get_object_or_404(Garaz, pk=garaz_id)
    try:
        searched_samochod = Samochod.objects.filter(
            garaz=garaz_id,
            model=request.GET['model']
        )
    except (KeyError, Samochod.DoesNotExist):
        return render(request, 'wynajem_limuzyn/detail.html', {
            'garaz': garaz,
            'error_message': "Nie znaleziono wyszukiwanego samochodu",
        })
    else:
        garaz.samochod_set.set(searched_samochod)
        return render(request, 'wynajem_limuzyn/detail.html', {'garaz': garaz})
def rent_samochod(request,samochod_id):
    samochod = get_object_or_404(Samochod, pk=samochod_id)
    if request.method == "POST":
        form = RentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.samochod = samochod
            post.save()
            samochod.wypozyczony = True
            samochod.save()
            garaz = get_object_or_404(Garaz, pk=samochod.garaz.pk)
            garaz.ilosc_dostepnych_samochodow = garaz.ilosc_dostepnych_samochodow - 1
            garaz.save()
            return redirect('wynajem_limuzyn:index')
    else:
        form = RentForm()

    return render(request, 'wynajem_limuzyn/rent_form.html', {'samochod': samochod,'form':form})
def give_back_car(request,samochod_id):

    if request.method == "POST":
        samochod = get_object_or_404(Samochod, pk=samochod_id)
        wypozyczenie = get_object_or_404(Wypozyczalnia, samochod_id=samochod_id,data_oddania=None)
        wypozyczenie.data_oddania = now()
        wypozyczenie.save()
        samochod.wypozyczony = False
        samochod.save()
        garaz = get_object_or_404(Garaz, pk=samochod.garaz.pk)
        garaz.ilosc_dostepnych_samochodow = garaz.ilosc_dostepnych_samochodow+1
        garaz.save()
        return redirect('wynajem_limuzyn:index')

szkielety_tworzenia_aplikacji/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">Zarządzanie wynajmem limuzyn</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

wynajem_limuzyn/templates/wynajem_limuzyn/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'wynajem_limuzyn/bootstrap.min.css' %}">

<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'wynajem_limuzyn:index' %}">Wynajem limuzyn</a>
    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <a class="nav-link">{{garaz.miasto}}, ul. {{garaz.ulica}} {{garaz.numer}}</a>
        </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'wynajem_limuzyn:search_samochod' garaz.id %}" method="get">
        <input class="form-control mr-sm-2" type="search" placeholder="Model" aria-label="Model" name="model">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Szukaj</button>
    </form>
</nav>
{% if garaz.samochod_set %}   
<div class="row row-cols-1 row-cols-md-3">
    {% for samochod in garaz.samochod_set.all %}
    <div class="col mb-4">
        <div class="card h-100">
            <img src="/media/{{samochod.zdjecie}}" class="card-img-top" alt="zdjecie samochodu">
            <div class="card-body">
                <h5 class="card-title">{{samochod.marka}} {{samochod.model}}</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">Liczba miejsc: {{samochod.liczba_miejsc}}</li>
                <li class="list-group-item">Data produkcji: {{samochod.data_produkcji}}</li>
                <li class="list-group-item">Euro 4:
                    {% if samochod.is_eco %}
                        TAK
                    {% else %}
                        NIE    
                    {% endif %}
                </li>
                <li class="list-group-item">Cena za godzine: {{samochod.cena}}</li>
            </ul>
            <div class="card-body">
                {% if samochod.wypozyczony is False %}
                <a href="/{{samochod.id}}/wypozycz/" class="btn btn-primary">Wynajmij</a>
                {% else %}
                <a href="wypozycz" class="btn btn-primary disabled" >Wynajmij</a>
                <form action="{% url 'wynajem_limuzyn:oddaj' samochod.id %}" method="post" >{% csrf_token %}
                    <input class="btn btn-primary" type="submit" value="Oddaj">
                 </form>
                {% endif %}
            </div>
        </div>
        </div>
    {% endfor %}
</div>
{% else %}
    <div class="alert alert-danger" role="alert">
        {% if error_message %}
            {{ error_message }}
        {% else %}
            Nie ma żadnych samochodów.
        {% endif %}
    </div>
{% endif %}    

wynajem_limuzyn/templates/wynajem_limuzyn/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'wynajem_limuzyn/bootstrap.min.css' %}">

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'wynajem_limuzyn:index' %}">Wynajem limuzyn</a>
  <form class="form-inline my-2 my-lg-0" action="{% url 'wynajem_limuzyn:search_miasto' %}" method="get">
    <input class="form-control mr-sm-2" type="search" placeholder="Miasto" aria-label="Miasto" name="miasto">
    <input class="form-control mr-sm-2" type="search" placeholder="Kod pocztowy" aria-label="Kod pocztowy" name="kod_pocztowy">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Szukaj</button>
  </form>
</nav>

{% if garaze %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Miasto</th>
                <th scope="col">Kod pocztowy</th>
                <th scope="col">Ulica</th>
                <th scope="col">Numer</th>
                <th scope="col">Ilosc samochodow</th>
                <th scope="col">Ilosc dostepnych samochodow</th>
            </tr>
        </thead>
        <tbody>
            {% for garaz in garaze %}
                <tr onclick="window.location='{% url 'wynajem_limuzyn:detail' garaz.id %}'">
                    <th scope="row">{{ garaz.id }}</th>
                    <td>{{ garaz.miasto }}</td>
                    <td>{{ garaz.kod_pocztowy }}</td>
                    <td>{{ garaz.ulica }}</td>
                    <td>{{ garaz.numer }}</td>
                    <td>{{ garaz.ilosc_samochodow }}</td>
                    <td>{{ garaz.ilosc_dostepnych_samochodow }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <div class="alert alert-danger" role="alert">
        {% if error_message %}
            {{ error_message }}
        {% else %}
            Nie ma żadnych garaży.
        {% endif %}
    </div>
{% endif %}    

wynajem_limuzyn/templates/wynajem_limuzyn/rent_form.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'wynajem_limuzyn/bootstrap.min.css' %}">

<h1>Wypożyczalnia</h1>
<div class="row row-cols-1 row-cols-md-3">
    <div class="card-body">
        <h2 class="card-title">Wypożyczasz {{samochod.marka}} {{samochod.model}}</h2>
        <img src="/media/{{samochod.zdjecie}}" class="card-img-top" alt="zdjecie samochodu">
        <form method="post" class="post-form">{% csrf_token %}
            <div class="form-group">
                {{ form.as_p }}
            </div>
            <input class="btn btn-primary" type="submit" value="Wypożycz">
        </form>
    </div>
</div>